name: Survi
version: '${project.version}'
main: fr.miuby.survi.Survi
api-version: '1.20'
authors: [Miuby]
description: Petite survi TeamAlpha
commands:
  sql:
    description: Requete sql
    usage: /<command> [sql]
  role:
    description: Change le role d'un joueur
    usage: /<command> [player] [role]
permissions:
  Survi.sql:
    default: op