# ─── Zone Village ───────────────────────────────────────────────────────────────
#
# Paliers de zone — triés par after-hours croissant.
#
# after-hours  : heures réelles après le début de partie avant activation du palier
# center-x/z   : centre de la zone rectangulaire pour ce palier
# half-width   : demi-largeur (axe X) en blocs depuis le centre
# half-depth   : demi-profondeur (axe Z) en blocs depuis le centre
# spawn        : coordonnées du point de spawn Village pour ce palier
# portal       : coordonnées intérieures (fakeblocks) du portail Village

stages:
  - after-hours: 0      # zone 0
    center-x: 64
    center-z: 960
    half-width: 64
    half-depth: 64
    spawn:
      x: 49.5
      y: 63
      z: 976.5
      yaw: -133.0
      pitch: -10.0
    portal:
      min-x: 55
      min-y: 63
      min-z: 978
      max-x: 55
      max-y: 65
      max-z: 979

  - after-hours: 0.03       # zone 1
    center-x: 64
    center-z: 896
    half-width: 64
    half-depth: 128
    spawn:
      x: 100.5
      y: 89
      z: 903.5
      yaw: -123.0
      pitch: 1.2
    portal:
      min-x: 98
      min-y: 89
      min-z: 895
      max-x: 99
      max-y: 91
      max-z: 895

  - after-hours: 0.06         # zone 2
    center-x: 128
    center-z: 896
    half-width: 128
    half-depth: 128
    spawn:
      x: 167.5
      y: 83
      z: 867.5
      yaw: -120.0
      pitch: 0.0
    portal:
      min-x: 179
      min-y: 83
      min-z: 868
      max-x: 179
      max-y: 85
      max-z: 869

  - after-hours: 0.09         # zone 3
    center-x: 128
    center-z: 768
    half-width: 128
    half-depth: 256
    spawn:
      x: 165.5
      y: 87
      z: 788.5
      yaw: -136.0
      pitch: 2.0
    portal:
      min-x: 145
      min-y: 88
      min-z: 788
      max-x: 145
      max-y: 90
      max-z: 787

  - after-hours: 0.12         # zone 4
    center-x: 128
    center-z: 768
    half-width: 256
    half-depth: 256
    spawn:
      x: 324.5
      y: 64
      z: 630.5
      yaw: -104.5
      pitch: -11.0
    portal:
      min-x: 310
      min-y: 63
      min-z: 633
      max-x: 310
      max-y: 65
      max-z: 632

  - after-hours: 0.15         # zone 5
    center-x: 256
    center-z: 512
    half-width: 256
    half-depth: 512
    spawn:
      x: 282.5
      y: 68
      z: 530.5
      yaw: -90.0
      pitch: 0.0
    portal:
      min-x: 269
      min-y: 68
      min-z: 531
      max-x: 269
      max-y: 73
      max-z: 529

  - after-hours: 0.18         # zone 6
    center-x: 512
    center-z: 512
    half-width: 512
    half-depth: 512
    spawn:
      x: 282.5
      y: 68
      z: 530.5
      yaw: -90.0
      pitch: 0.0
    portal:
      min-x: 269
      min-y: 68
      min-z: 531
      max-x: 269
      max-y: 73
      max-z: 529